<a href="https://colab.research.google.com/github/Naveen-gale/deep_learning/blob/main/dpl_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [ ]:
df.head()

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.10             34               9            1
1           0.15             30               8            1
2           0.20             26               7            1
3           0.25             22               4            0
4           0.40             28               8            0

In [ ]:
X= df.drop("needs_water", axis=1)
y=df["needs_water"]

In [ ]:
X_min= X.min()
X_max= X.max()
X_scale= (X-X_min)/(X_max-X_min + 1e-8)

In [ ]:
X_scale

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scale, y, test_size=0.33, random_state=42, stratify=y)

In [ ]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')


])

In [ ]:
model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - accuracy: 0.4000 - loss: 0.7106 - val_accuracy: 0.5000 - val_loss: 0.7009
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7068 - val_accuracy: 0.5000 - val_loss: 0.6999
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.7051 - val_accuracy: 0.5000 - val_loss: 0.6989
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4000 - loss: 0.7035 - val_accuracy: 0.5000 - val_loss: 0.6986
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7015 - val_accuracy: 0.5000 - val_loss: 0.6979
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7008 - val_accuracy: 0.5000 - val_loss: 0.6971
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.6989 - val_accuracy: 0.5000 - val_loss: 0.6964
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6000 - loss: 0.6986 - val_accuracy: 0.5000 - val_loss: 0.6956
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6961 - val_accuracy: 0.5000 - val_loss: 0.6947
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6950 - val_accuracy: 0.5000 - val_loss: 0.6939
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6930
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6000 - loss: 0.6925 - val_accuracy: 0.5000 - val_loss: 0.6926
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6912 - val_accuracy: 0.5000 - val_loss: 0.6922
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6901 - val_accuracy: 0.5000 - val_loss: 0.6912
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6000 - loss: 0.6889 - val_accuracy: 0.5000 - val_loss: 0.6902
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6872 - val_accuracy: 0.5000 - val_loss: 0.6892
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6854 - val_accuracy: 0.5000 - val_loss: 0.6886
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6845 - val_accuracy: 0.5000 - val_loss: 0.6882
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6000 - loss: 0.6843 - val_accuracy: 0.5000 - val_loss: 0.6880
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6837 - val_accuracy: 0.5000 - val_loss: 0.6876
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7000 - loss: 0.6825 - val_accuracy: 0.5000 - val_loss: 0.6872
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7000 - loss: 0.6822 - val_accuracy: 0.5000 - val_loss: 0.6867
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7000 - loss: 0.6815 - val_accuracy: 0.5000 - val_loss: 0.6866
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6812 - val_accuracy: 0.5000 - val_loss: 0.6861
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7000 - loss: 0.6804 - val_accuracy: 0.5000 - val_loss: 0.6856
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7000 - loss: 0.6793 - val_accuracy: 0.6667 - val_loss: 0.6849
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6000 - loss: 0.6778 - val_accuracy: 0.6667 - val_loss: 0.6846
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6775 - val_accuracy: 0.6667 - val_loss: 0.6841
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6000 - loss: 0.6762 - val_accuracy: 0.6667 - val_loss: 0.6837
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6763 - val_accuracy: 0.6667 - val_loss: 0.6835
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6747 - val_accuracy: 0.6667 - val_loss: 0.6832
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6740 - val_accuracy: 0.6667 - val_loss: 0.6829
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6000 - loss: 0.6740 - val_accuracy: 0.6667 - val_loss: 0.6829
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6000 - loss: 0.6738 - val_accuracy: 0.6667 - val_loss: 0.6826
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6000 - loss: 0.6722 - val_accuracy: 0.6667 - val_loss: 0.6823
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6721 - val_accuracy: 0.6667 - val_loss: 0.6824
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6710 - val_accuracy: 0.6667 - val_loss: 0.6819
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6000 - loss: 0.6710 - val_accuracy: 0.6667 - val_loss: 0.6819
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6704 - val_accuracy: 0.6667 - val_loss: 0.6815
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6695 - val_accuracy: 0.6667 - val_loss: 0.6811
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6692 - val_accuracy: 0.8333 - val_loss: 0.6804
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6683 - val_accuracy: 0.8333 - val_loss: 0.6801
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6669 - val_accuracy: 0.8333 - val_loss: 0.6798
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7000 - loss: 0.6666 - val_accuracy: 0.8333 - val_loss: 0.6794
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7000 - loss: 0.6655 - val_accuracy: 0.8333 - val_loss: 0.6791
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6648 - val_accuracy: 0.8333 - val_loss: 0.6788
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7000 - loss: 0.6651 - val_accuracy: 0.8333 - val_loss: 0.6785
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7000 - loss: 0.6642 - val_accuracy: 0.8333 - val_loss: 0.6780
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8000 - loss: 0.6634 - val_accuracy: 0.8333 - val_loss: 0.6775
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6620 - val_accuracy: 0.8333 - val_loss: 0.6771
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6621 - val_accuracy: 0.8333 - val_loss: 0.6771
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6609 - val_accuracy: 0.8333 - val_loss: 0.6767
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6607 - val_accuracy: 0.8333 - val_loss: 0.6764
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6601 - val_accuracy: 0.8333 - val_loss: 0.6761
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6595 - val_accuracy: 0.8333 - val_loss: 0.6756
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6610 - val_accuracy: 0.8333 - val_loss: 0.6754
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6579 - val_accuracy: 0.8333 - val_loss: 0.6750
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6584 - val_accuracy: 0.8333 - val_loss: 0.6745
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6567 - val_accuracy: 0.8333 - val_loss: 0.6743
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9000 - loss: 0.6565 - val_accuracy: 0.8333 - val_loss: 0.6739
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6573 - val_accuracy: 0.8333 - val_loss: 0.6738
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6559 - val_accuracy: 0.8333 - val_loss: 0.6733
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6549 - val_accuracy: 0.8333 - val_loss: 0.6727
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6542 - val_accuracy: 0.8333 - val_loss: 0.6723
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6532 - val_accuracy: 0.8333 - val_loss: 0.6719
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8000 - loss: 0.6553 - val_accuracy: 0.8333 - val_loss: 0.6715
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8000 - loss: 0.6526 - val_accuracy: 0.8333 - val_loss: 0.6712
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6514 - val_accuracy: 0.8333 - val_loss: 0.6709
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6516 - val_accuracy: 0.6667 - val_loss: 0.6704
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8000 - loss: 0.6511 - val_accuracy: 0.5000 - val_loss: 0.6700
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8000 - loss: 0.6500 - val_accuracy: 0.5000 - val_loss: 0.6698
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8000 - loss: 0.6495 - val_accuracy: 0.8333 - val_loss: 0.6695
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8000 - loss: 0.6484 - val_accuracy: 0.8333 - val_loss: 0.6693
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8000 - loss: 0.6485 - val_accuracy: 0.6667 - val_loss: 0.6688
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8000 - loss: 0.6479 - val_accuracy: 0.8333 - val_loss: 0.6686
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8000 - loss: 0.6471 - val_accuracy: 0.8333 - val_loss: 0.6684
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8000 - loss: 0.6472 - val_accuracy: 0.8333 - val_loss: 0.6683
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6454 - val_accuracy: 0.8333 - val_loss: 0.6681
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8000 - loss: 0.6458 - val_accuracy: 0.8333 - val_loss: 0.6679
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6440 - val_accuracy: 0.8333 - val_loss: 0.6676
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6451 - val_accuracy: 0.8333 - val_loss: 0.6672
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8000 - loss: 0.6431 - val_accuracy: 0.8333 - val_loss: 0.6672
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9000 - loss: 0.6418 - val_accuracy: 0.8333 - val_loss: 0.6670
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6416 - val_accuracy: 1.0000 - val_loss: 0.6669
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6410 - val_accuracy: 0.8333 - val_loss: 0.6667
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6414 - val_accuracy: 1.0000 - val_loss: 0.6667
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6410 - val_accuracy: 0.8333 - val_loss: 0.6663
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6389 - val_accuracy: 0.8333 - val_loss: 0.6658
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8000 - loss: 0.6383 - val_accuracy: 0.8333 - val_loss: 0.6658
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6368 - val_accuracy: 0.8333 - val_loss: 0.6655
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9000 - loss: 0.6361 - val_accuracy: 0.8333 - val_loss: 0.6653
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6376 - val_accuracy: 0.8333 - val_loss: 0.6653
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6347 - val_accuracy: 1.0000 - val_loss: 0.6650
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6339 - val_accuracy: 0.8333 - val_loss: 0.6647
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9000 - loss: 0.6353 - val_accuracy: 0.8333 - val_loss: 0.6641
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9000 - loss: 0.6333 - val_accuracy: 0.8333 - val_loss: 0.6638
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9000 - loss: 0.6324 - val_accuracy: 0.8333 - val_loss: 0.6633
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6316 - val_accuracy: 0.8333 - val_loss: 0.6630
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8000 - loss: 0.6311 - val_accuracy: 0.8333 - val_loss: 0.6630
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9000 - loss: 0.6305 - val_accuracy: 0.8333 - val_loss: 0.6625