<a href="https://colab.research.google.com/github/Naveen-gale/deep_learning/blob/main/lsm_and_rus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [83]:
df = pd.read_csv("qoute_dataset.csv")

In [84]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [85]:
df.value_counts().sum()

np.int64(3038)

In [86]:
df.isnull().sum()

quote     0
Author    0
dtype: int64

In [87]:
df.duplicated().sum()

np.int64(0)

In [88]:
df.shape

(3038, 2)

In [89]:
quote = df['quote']

In [90]:
quote.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [91]:
def lower_case(text):
   text = text.lower()
   return text

In [92]:
quote= quote.apply(lower_case)

In [93]:
quote.head()

0    “the world as we have created it is a process ...
1    “it is our choices, harry, that show what we t...
2    “there are only two ways to live your life. on...
3    “the person, be it gentleman or lady, who has ...
4    “imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [94]:
import pandas as pd
import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [95]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [96]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess(text):

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    # remove space
    text = text.strip()

    # Tokenization
    tokens = word_tokenize(text)

    # Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    # Join words
    return " ".join(tokens)

In [97]:
quote = quote.apply(lambda x: preprocess(x))

In [98]:
quote.head()

0    world created process thinking changed without...
1                  choice harry show truly far ability
2    two way live life one though nothing miracle t...
3    person gentleman lady pleasure good novel must...
4    imperfection beauty madness genius better abso...
Name: quote, dtype: object

In [99]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [100]:
vac_size = 10000
tokenizer = Tokenizer(vac_size)
tokenizer.fit_on_texts(quote)

In [101]:
qoutes = tokenizer.word_index
print(len(word))
list(word.items())[:5]

7502

[('love', 1), ('life', 2), ('one', 3), ('thing', 4), ('like', 5)]

In [102]:
sequence = tokenizer.texts_to_sequences(quote)

In [103]:
print(sequence)

[[14, 788, 995, 184, 685, 40, 627, 184], [210, 268, 246, 360, 193, 551], [115, 19, 23, 2, 3, 211, 33, 789, 211, 57, 789], [34, 1676, 628, 412, 20, 1154, 49, 2129, 226], [1373, 194, 629, 512, 71, 552, 1155, 552, 630], [153, 116, 26, 330, 180, 116, 26, 361], [71, 1156, 96], [1157, 94, 312, 19, 201, 165], [56, 5, 686, 1158, 8, 9, 218, 513, 300], [32, 40, 889, 5, 9, 154], [2, 11, 76, 25, 60, 631, 55, 1677, 92, 20, 105, 29, 362, 25, 60, 631, 83, 52, 632, 313, 5, 687, 77, 36, 17, 3, 171, 57, 130, 84, 82, 52, 6, 35, 17, 283, 77, 790, 11, 82, 52, 14, 514, 91, 632, 36, 17, 515, 138, 31, 373, 314, 41, 60, 256, 27, 53, 46, 46, 118, 8, 39, 2130, 118, 8, 39, 269, 11, 159, 17, 57, 553, 87, 89, 25, 890, 791, 553, 57, 86, 167, 212, 16, 16, 16, 58, 6, 2131, 86, 172, 315, 86, 1374, 1375, 86, 688, 2, 110, 4, 104, 41, 163], [69, 73, 516, 725, 173, 374, 41, 173, 52], [53, 792, 793, 90, 168, 6, 131], [61, 98, 155, 96, 61, 1, 1, 93, 76, 316, 2132, 301, 302, 115, 61, 8, 237, 174, 11, 190, 588, 13, 891, 794, 88, 247, 185, 212, 795, 46, 61, 184, 30, 270, 32, 46, 105, 9, 2133, 27, 6, 127, 6, 70, 6, 1678, 6, 342, 46, 163, 11, 107, 35, 9, 11, 331, 460, 316], [5, 689, 343, 589, 1159, 344, 480, 1679, 139], [61, 227, 2134, 17, 13, 1680, 633], [690, 1, 138, 634, 690, 363, 1681, 634, 690, 481, 2135, 634, 690, 2, 119, 634], [726, 1, 726, 332, 11, 635, 1376], [20, 52, 20, 15, 2136, 691, 892, 2], [2, 219, 18, 247, 590], [1, 40, 257, 1, 461, 40, 364, 727, 1, 19, 9, 19, 284, 1160, 122, 156, 636, 122, 1160, 123, 554, 101, 271], [30, 413, 637, 146, 1682, 270, 111], [555, 7, 12, 1], [177, 13, 796, 1377, 11, 996, 49, 283, 13, 796, 1683, 11, 692], [194, 101, 1378, 61, 480, 12, 12, 46, 226, 1379, 1378, 365, 101], [345, 1684, 84, 3, 285, 2137], [10, 134, 462, 48, 439, 440, 10, 462, 48, 439, 440], [258, 23, 40, 1380, 24, 366, 23, 2138, 160, 91, 317, 638, 553, 1685], [1381, 29, 1382, 393, 29, 1161], [3, 20, 4, 195, 482, 51, 113], [48, 4, 9, 117, 128, 118, 17], [375, 797, 129, 172, 268, 175, 89, 124], [92, 142, 60, 127, 108, 39, 3, 228, 286], [18, 73, 4, 191, 4, 73, 1], [2139, 67, 119, 287, 73, 517], [66, 1, 64, 1162, 87, 127], [48, 9, 120], [333, 9, 202, 131], [16, 1383, 1163, 102, 334], [8, 483, 160], [591, 2, 229, 2, 518, 21, 2140, 26, 8, 48, 2, 3], [8, 29, 639, 686, 556, 72, 15, 95, 72, 1164], [58, 125, 893, 117, 181, 3], [11, 56, 190, 11, 75], [2, 5, 2141, 1686, 86, 1384, 49, 86, 557], [124, 514, 26, 2142, 798, 1687, 688, 101, 799, 484], [394, 83, 367, 87, 1, 1165, 87, 58, 441, 238], [318, 22, 140], [76, 38, 376, 186], [1, 213, 99, 19, 377, 13, 1, 894, 1, 319, 1, 997], [33, 37, 59, 52, 1166, 284, 7, 269, 485], [3, 4, 30, 32, 998], [20, 486, 463, 999, 191, 83, 395, 14, 167, 39, 38, 1], [2143, 37, 519, 2144, 182, 13, 195, 23, 2145, 195, 22, 2, 895, 195], [48, 15, 142, 93, 132, 13, 142, 93, 184], [346, 512, 896, 512, 800], [239, 5, 1000, 1688], [52, 1167, 15], [3, 196, 111, 271, 78, 214, 182, 62, 95, 1001, 196, 22, 3, 801, 18], [2, 147, 1002, 2, 897], [50, 364, 2146, 79, 2147, 464, 24, 144, 219, 464, 693, 150, 24, 20, 219, 464, 640, 2148, 33, 219, 464, 11, 24, 220], [6, 150, 137, 34, 155, 106], [77, 1689, 1, 44, 367, 2149, 51, 5], [1, 802, 1, 75, 27, 2150, 803, 230, 10, 11, 221, 1003, 1385, 49, 46, 3, 47, 592, 898, 1386, 899, 1690, 64, 1168, 487, 2151, 1004, 641, 1387, 2152, 1691, 1387, 641, 231, 2153, 2154, 70, 230, 116, 1388, 2155, 2156, 1, 802], [1389, 240], [1005, 378, 268, 1005, 139, 23, 40, 1], [33, 442, 232, 2157, 1006], [804, 32, 215, 215, 42, 2158, 1390, 520, 2159, 150, 593, 272, 135, 32, 151, 213, 2160, 315, 488, 2161, 168, 689], [8, 35, 2162, 2163, 558], [489, 347, 3, 102, 36, 694, 36, 248, 94, 1692, 395, 1693, 28, 559, 22, 347, 60, 347], [396, 30, 12, 79, 1169, 42, 183, 900, 136], [7, 8, 17, 335, 360, 728, 2, 49, 465], [347, 214, 67, 375, 7, 1170, 521, 490, 167, 178, 4], [13, 238, 13, 44, 13, 901, 13, 315, 466, 13, 13, 153], [59, 1391, 15, 25, 215, 132, 197, 1007, 467, 1392, 52, 42, 241, 1393, 642, 179, 5, 87, 220, 41, 211], [169, 203, 28, 3, 805, 233, 491], [61, 31, 28, 806, 28, 3, 106, 643, 118, 1171, 18, 14, 23, 3], [348, 1008, 138, 142, 1172], [204, 147, 60, 35, 60, 145], [1173, 15, 7, 2164, 6, 48], [177, 8, 114, 185, 8, 560, 75, 135], [628, 393, 2165, 1009, 2166, 1, 1, 2167, 80], [77, 12, 36, 11, 210, 44, 273, 77, 288, 320, 20, 102, 468, 2168, 594, 492, 595, 1694, 77, 2169, 2170], [1394, 1695, 5, 132, 41, 1174, 3, 1696, 4, 15, 289, 151, 1010, 1697, 334], [7, 59, 1, 85, 2171, 13, 91, 22, 14, 2172, 30, 32, 2173, 469, 2174, 88, 397, 64, 2175, 2176, 1698, 1699, 398], [32, 168, 72, 205, 132, 439, 440], [1011, 2177, 63, 82, 18, 1175, 522, 82, 290], [97, 119, 2178, 97, 2, 26, 2, 729, 1395, 112, 12], [125, 399, 269, 19, 109, 14, 92, 1396, 807], [58, 1700, 58, 349, 2179, 22, 22, 57, 93], [92, 730, 1397, 110, 596, 4, 561, 1701, 73, 1398], [28, 3, 50, 108, 112, 12, 112, 35, 23, 2, 19, 10], [112, 1176, 395, 517], [69, 170, 186, 116, 59], [71, 29, 127, 92, 2180, 125], [8, 59, 131, 34, 1012, 4, 202, 808, 1399, 129, 523, 183, 109], [157, 15, 10, 470, 15, 644, 902, 157, 134], [8, 54, 92, 7, 903], [34, 34, 76, 191], [67, 66, 15, 904, 66, 2181, 86, 809], [142, 93, 274, 597], [28, 1400, 2182, 64, 1702, 11, 185, 350, 12, 152, 1703, 53, 1703, 562, 221, 161, 6, 443, 82], [81, 15, 64, 12], [115, 4, 493, 206, 88, 896, 28, 221, 206], [336, 40, 15, 5, 321, 40, 74], [31, 51, 67, 6, 76, 76, 6, 67], [143, 108, 1013, 444, 5, 104, 291, 3157, 5, 118, 8, 3158, 5, 104, 291, 3159, 23, 5, 414, 175], [9, 25, 1, 53, 123, 554, 187, 415, 71, 65], [23, 44, 72], [70, 197, 22, 14], [275, 43, 2183, 57, 94, 400, 2, 17], [10, 9, 26, 5, 69, 20, 62, 645, 3160, 810], [6, 183, 445, 61, 3161, 183, 248, 61, 3162, 1014, 52], [54, 92, 6, 77, 75], [332, 376, 80, 3, 26, 31, 78, 79, 3], [94, 400, 7, 150, 21, 7, 150, 7, 8, 150, 114, 51], [52, 38, 9, 85, 1], [23, 1177, 4, 14, 7, 276], [16, 322, 374, 33, 2184, 41], [318, 695, 318, 133, 138, 695, 138, 1], [23, 112, 272, 117, 23, 136], [491, 1, 13, 443], [40, 195, 2, 37, 185], [1704, 55, 6, 131, 401, 43, 188], [14, 731, 167, 11, 24, 93, 446, 3163], [1401, 335, 3, 3164, 3165, 3166, 899, 3167, 2185, 811, 3, 22, 4, 812, 130, 1178, 379, 323, 3168, 3169, 1179, 1705, 3170, 3171, 4, 53, 813, 70, 4, 1015, 88, 2186, 563, 61, 22, 335, 3, 22, 512, 7, 335, 72, 13, 70, 14, 3], [1016, 4, 1402, 259, 1180], [58, 57, 219, 169, 7, 70, 117, 35, 17, 4, 17, 121, 1181, 130, 44, 58, 125, 893, 117, 181, 3, 55, 20, 4, 123, 416, 71, 4, 123, 174], [71, 1156, 96], [2187, 90, 905, 4, 148, 3, 417, 3172, 1403, 149, 641, 1706, 732, 1182, 418, 1403, 1183, 65, 646], [2, 360, 58, 39, 38, 402, 290, 14, 109, 54, 4, 143, 8, 1404, 78, 74, 2188, 57, 31, 373, 10, 260, 598, 106, 158, 65, 8, 36, 84, 906, 8, 1184, 81, 1185, 2, 1707, 24, 564, 219, 53, 292, 54, 257, 598, 1708, 2189, 249, 2190, 190, 11, 333, 8, 127, 141, 11, 51, 5, 20, 72, 180, 524, 246, 4, 11, 403, 47, 110, 8, 2191, 1709, 3173, 814, 3174, 109, 471, 13, 1, 4, 377, 2192, 7, 907, 293, 183, 116, 3175, 696, 733, 641, 27, 1710, 136, 222, 734, 36, 68, 815, 3176, 5, 324, 2193, 377, 3177, 1186, 525, 351, 105, 1405, 2, 3178, 148, 276, 1393, 241, 115, 32, 261, 29, 95, 32, 165, 16, 816, 163, 137, 1187, 104, 66, 3179, 1406, 39, 25, 419, 908, 2194, 4, 8, 2195, 116, 1711, 9, 207, 34, 403, 13, 34, 30, 2196, 57, 325, 4, 526, 67, 5, 1017, 647, 380, 1018, 418, 47, 352, 648, 1188, 214, 27, 257, 104, 565, 61, 230, 3, 32, 1407, 27, 216, 1, 420, 8, 1019, 277, 39, 802, 19, 735, 27, 51, 84, 412, 50, 124, 998, 39, 303, 257, 84, 52, 803, 74, 649, 527, 1167, 99, 2, 351, 402, 259, 2197, 1408, 106, 1712, 257, 105, 2], [736, 3180, 1389, 3181, 168, 218, 3182, 737, 1713, 3183, 1409, 192, 151, 3184, 133, 650, 151, 3185, 151, 1714, 3186, 3187, 151, 1410], [34, 1676, 628, 412, 20, 1154, 49, 2129, 226], [210, 268, 246, 360, 193, 551], [1373, 194, 629, 512, 71, 552, 1155, 552, 630], [115, 19, 23, 2, 3, 211, 33, 789, 211, 57, 789], [1411, 65, 150, 23], [20, 52, 20, 15, 2136, 691, 892, 2], [48, 651, 1, 19, 123, 554, 1189], [3188, 18, 164, 140], [439, 440, 84, 54, 18, 652, 276, 54, 18, 652, 3189], [333, 1715, 13, 394, 394, 26, 9, 333], [71, 527, 599, 566, 79, 333, 203, 2198, 520], [642, 39, 294, 1412, 12, 3190, 2199, 2200], [2, 219, 18, 247, 590], [738, 337, 272, 739, 345, 697, 63, 241, 528], [1157, 94, 312, 19, 201, 165], [726, 1, 726, 332, 11, 635, 1376], [690, 1, 138, 634, 690, 363, 1681, 634, 690, 481, 2135, 634, 690, 2, 119, 634], [26, 48, 1190, 26, 48], [56, 5, 686, 1158, 8, 9, 218, 513, 300], [1, 40, 257, 1, 461, 40, 364, 727, 1, 19, 9, 19, 284, 1160, 122, 156, 636, 122, 1160, 123, 554, 101, 271], [61, 227, 2134, 17, 13, 1680, 633], [6, 173, 24, 123, 75], [600, 494, 15, 26, 82, 52, 129, 494, 231, 48], [3191, 909, 20], [72, 1020, 1021, 2201, 156, 393, 393, 207, 404, 404, 1191, 393, 3192, 14], [1, 181, 3193, 121, 529, 338, 2202, 3194, 234, 278, 86, 910, 3195, 910, 2, 911, 3196, 3197, 8, 3198, 2203], [45, 1, 728, 147, 11, 802, 214, 636, 214, 27, 89, 38, 29, 129, 631], [5, 689, 343, 589, 1159, 344, 480, 1679, 139], [591, 2, 229, 2, 518, 21, 2140, 26, 8, 48, 2, 3], [32, 40, 889, 5, 9, 154], [8, 178, 817, 272, 61, 215, 32, 272, 91], [698, 96, 38, 46, 303, 284, 38, 698, 46, 170], [589, 172, 405, 807, 3199, 818, 250, 25, 9, 9, 3, 3200, 362, 17], [262, 18, 11, 18, 421], [8, 483, 160], [30, 413, 637, 146, 1682, 270, 111], [2, 11, 76, 25, 60, 631, 55, 1677, 92, 20, 105, 29, 362, 25, 60, 631, 83, 52, 632, 313, 5, 687, 77, 36, 17, 3, 171, 57, 130, 84, 82, 52, 6, 35, 17, 283, 77, 790, 11, 82, 52, 14, 514, 91, 632, 36, 17, 515, 138, 31, 373, 314, 41, 60, 256, 27, 53, 46, 46, 118, 8, 39, 2130, 118, 8, 39, 269, 11, 159, 17, 57, 553, 87, 89, 25, 890, 791, 553, 57, 86, 167, 212, 16, 16, 16, 58, 6, 2131, 86, 172, 315, 86, 1374, 1375, 86, 688, 2, 110, 4, 104, 41, 163], [69, 73, 516, 725, 173, 374, 41, 173, 52], [1, 1716, 1, 3201, 1413, 11, 17], [555, 7, 12, 1], [28, 912, 2204, 28, 912, 53, 58], [601, 1192, 3202, 3203, 126, 129], [8, 12, 128, 84, 1, 219, 3204, 2205, 401, 3205, 3206, 80], [53, 792, 793, 90, 168, 6, 131], [48, 15, 142, 93, 132, 13, 142, 93, 184], [1, 1414, 111, 78, 34, 1193], [177, 13, 796, 1377, 11, 996, 49, 283, 13, 796, 1683, 11, 692], [57, 422, 124], [16, 1383, 1163, 102, 334], [56, 567, 653, 103, 494, 3207, 29, 447, 339], [6, 22, 4, 22], [61, 98, 155, 96, 61, 1, 1, 93, 76, 316, 2132, 301, 302, 115, 61, 8, 237, 174, 11, 190, 588, 13, 891, 794, 88, 247, 185, 212, 795, 46, 61, 184, 30, 270, 32, 46, 105, 9, 2133, 27, 6, 127, 6, 70, 6, 1678, 6, 342, 46, 163, 11, 107, 35, 9, 11, 331, 460, 316], [55, 204, 1717, 233, 325], [1, 124, 3208, 54, 124], [8, 29, 639, 686, 556, 72, 15, 95, 72, 1164], [8, 181, 177, 1194, 15], [48, 9, 120], [55, 48, 15, 530, 1195, 2206, 2207, 116, 1415, 2208, 14, 8, 178, 68, 174, 366, 139, 88, 48, 15], [2, 147, 1002, 2, 897], [66, 1, 64, 1162, 87, 127], [194, 101, 1378, 61, 480, 12, 12, 46, 226, 1379, 1378, 365, 101], [375, 797, 129, 172, 268, 175, 89, 124], [345, 1684, 84, 3, 285, 2137], [28, 263, 119, 6, 10, 219], [3, 368, 132, 15, 278, 132], [2139, 67, 119, 287, 73, 517], [258, 23, 40, 1380, 24, 366, 23, 2138, 160, 91, 317, 3209, 638, 553, 1685], [10, 134, 462, 48, 439, 440, 10, 462, 48, 439, 440], [28, 1, 21, 3210, 2209, 21, 799, 42, 22, 602, 101, 3211, 28, 1, 28, 1022, 2210, 325, 412, 188, 84, 4, 28, 1, 9, 1, 1416, 3212, 3213, 1718, 3214, 36, 32, 1719, 3215, 819, 9, 349, 1720, 175, 91, 45, 1], [1381, 29, 1382, 393, 29, 1161], [33, 403, 221, 531, 26, 531, 79, 94, 1721, 531, 2, 1722, 3216, 304, 593, 568, 94, 96, 78, 27, 74, 16, 72], [642, 51, 66, 2211, 125, 17, 149], [820, 1, 121, 34, 3217, 21, 1417, 628, 3, 84, 1, 1418, 3218, 235, 21, 6, 471, 1723, 264, 3219, 1011, 290, 2212, 86, 654], [92, 142, 60, 127, 108, 39, 3, 228, 286], [55, 7, 3220, 3221, 3222], [1, 62, 101, 67, 561, 3223, 3224, 2213, 699, 3225, 1, 67, 1419, 279, 821, 101, 603, 3226, 3227, 561, 1, 21, 134, 210, 2214, 3228], [6, 29, 250, 29, 127, 3229, 31, 127, 5, 210], [1420, 495, 107, 11, 67], [], [48, 4, 9, 117, 128, 118, 17], [52, 1167, 15], [126, 3230, 305, 206, 3231, 114, 208, 7, 637, 3232, 3233, 144, 472], [330, 913, 604, 1196, 170, 1197, 423], [3, 20, 4, 195, 482, 51, 113], [39, 1421, 1198, 30, 12, 198, 290, 280, 17, 336, 48, 15], [1, 5, 418, 53, 22, 51], [2, 10, 9, 107, 199, 28, 85, 167, 603, 42], [3, 196, 111, 271, 78, 214, 182, 62, 95, 1001, 196, 22, 3, 801, 18], [33, 37, 59, 52, 1166, 284, 7, 269, 485], [18, 73, 4, 191, 4, 73, 1], [189, 3234, 134, 189, 2215, 189, 3235, 258, 201, 189, 8, 3236, 189, 271, 75, 220, 134, 75], [7, 8, 17, 335, 360, 728, 2, 49, 465], [2, 5, 2141, 1686, 86, 1384, 49, 86, 557], [23, 569, 10, 23, 569, 3237, 3, 32, 8, 23, 40], [7, 13, 74, 649, 237, 822, 50, 142, 10, 84, 74, 649, 740, 34, 246, 57, 496, 68, 34, 816, 914, 70, 2, 84, 74, 649, 519, 207, 34, 118, 45, 295, 369, 570, 3238, 1199, 23, 74, 649, 136, 2216, 522, 74, 649, 36, 2, 1200, 78, 1422, 200, 74, 649, 532, 1201, 369, 416, 2217, 64, 700, 246, 3239, 1724, 256, 27, 214, 135, 133, 29, 11, 1023, 350, 823, 2, 2218, 1725, 1726], [6, 1, 38, 130, 237, 1, 915, 265, 130], [59, 1391, 15, 25, 215, 132, 197, 1007, 467, 1392, 52, 42, 241, 1393, 642, 179, 5, 87, 220, 41, 211], [1, 8, 518, 1024, 119, 518, 6, 9, 3240, 916, 518, 3241, 2219, 1202, 518, 1025, 571, 518, 3242, 3243, 3244], [188, 1026, 25, 1027, 5, 188, 2220, 1026, 406, 180, 462, 226, 406, 180, 2221, 3245, 58, 4, 76, 3246, 1028, 3247, 3248, 265, 351, 3249, 1727, 314, 1203, 47, 1203, 102, 1203, 188, 25, 1203, 5, 188, 183, 2222, 1423, 251, 3250, 239, 215, 44], [76, 38, 376, 186], [11, 56, 190, 11, 75], [1389, 240], [64, 1195, 2, 64, 1195, 39, 38, 805, 3251, 2223, 1171, 123, 1728, 3252, 3253, 241, 3254, 1], [346, 512, 896, 512, 800], [396, 30, 12, 79, 1169, 42, 183, 900, 136], [48, 6, 2224, 53, 261], [347, 214, 67, 375, 7, 1170, 521, 490, 167, 178, 4], [3, 4, 30, 32, 998], [37, 1729, 701, 3255, 467, 81, 605, 40, 3256, 182, 56], [6, 74, 3257, 74, 321, 2225], [702, 741, 702], [3, 49, 16, 917, 15, 21, 824, 129, 43, 234, 70, 18], [187, 1730, 1424, 2], [12, 368, 3258, 1204, 12], [197, 66, 288, 12, 21, 3259, 21, 3260, 23, 22, 12, 362, 362, 12, 655, 18], [4, 70, 52, 200, 2, 87, 145, 473], [104, 15, 10, 48, 1205, 470, 242, 49, 157], [825, 264, 21, 1731, 2226, 1, 1, 112, 2, 252, 1], [1, 802, 1, 75, 27, 2150, 803, 230, 10, 11, 221, 1003, 1385, 49, 46, 3, 47, 592, 898, 1386, 899, 1690, 64, 1168, 487, 2151, 1004, 641, 1387, 2152, 1691, 1387, 641, 231, 2153, 2154, 70, 230, 116, 1388, 2155, 2156, 1, 802], [555, 2, 3261, 9, 28, 3262, 6, 23, 3263, 205, 3264, 3265, 221, 122, 1425], [1394, 1695, 5, 132, 41, 1174, 3, 1696, 4, 15, 289, 151, 1010, 1697, 334], [124, 514, 26, 2142, 798, 1687, 688, 101, 799, 484], [19, 1732, 286, 322], [38, 1, 19, 203, 259, 51, 641, 1029], [10, 24, 206, 3266, 1426, 1030], [17, 414, 3267, 161, 1427], [169, 203, 28, 3, 805, 233, 491], [2227, 3268, 1428, 248, 1428, 3269, 3270, 21, 2227, 826, 3271, 3272, 166, 221], [15, 14, 241, 2228, 15, 246, 14, 3273], [1005, 378, 268, 1005, 139, 23, 40, 1], [239, 5, 1000, 1688], [33, 442, 232, 2157, 1006], [8, 48, 15, 10, 8, 7, 10, 23, 2, 10, 8, 918, 3274, 10, 10, 10, 23, 51, 1429, 1430, 2229, 1431, 1206, 216, 277, 2, 3275, 1191], [730, 1207, 533, 149, 3276, 2230, 3277, 656, 68, 1031, 101, 223, 3278, 3279, 21, 1031], [394, 83, 367, 87, 1, 1165, 87, 58, 441, 238], [827, 83, 3280, 83, 48, 827, 83, 2231, 534, 15, 497, 703, 364, 2232, 484, 81, 15, 827, 83, 828, 15, 10, 48, 334, 1208, 919, 3281, 83, 48, 118, 9, 16, 2233, 15, 1158, 316, 3, 1733, 164, 1032, 1432, 3, 1734, 249, 312, 15, 10, 22, 1195, 3282, 1735, 474, 168, 15, 3283, 15, 1736, 50, 591, 8, 1209, 3284, 474, 1210, 1033, 3285, 83, 132, 535, 1034, 1736, 829, 69, 3286, 3287, 3288, 3289, 1433, 1035, 316, 102, 3290, 274, 240, 14, 1007, 247, 232, 160, 46, 3291, 83, 48, 5, 1737, 266, 5, 3292, 78, 639, 3293, 9, 59, 13, 3294, 22, 108, 98, 3295, 3296, 131, 31, 830, 2234, 3297, 3298, 316, 188, 606, 462, 266, 1, 2235, 37, 5, 3299, 273, 827, 83, 48, 46, 15, 3300, 1434, 3301, 46, 697, 43, 475, 293, 46, 3302, 2236, 3303, 3304, 35, 9, 131, 43, 1, 131, 9, 346, 15, 187, 63, 316, 60, 153, 11, 2, 64, 5, 831, 15, 8, 1738, 3305, 46, 1435, 3306, 1211, 3307, 131, 66, 125, 248, 43, 4, 2237, 361, 2238, 3308, 99, 3309, 83, 48, 9, 604, 16, 465, 3310, 83, 48, 131, 4, 49, 36, 99, 16, 157, 3311, 213, 85, 832, 2, 306, 1739, 3312, 1212, 57, 83, 48, 131, 7, 5, 397, 3313, 536, 2239, 3314, 39, 83, 48, 86, 271, 39, 3315, 15, 636, 2240, 11, 639, 686, 212, 61, 146, 1436, 281, 16, 36, 68, 1740, 203, 397, 15, 124, 16, 3316, 3317, 513, 537, 3318, 1437, 3319, 3320, 287, 12, 316, 920, 3321, 163, 152, 424, 27, 1205, 1213, 3322, 636, 242, 157, 126, 2, 381, 607, 304, 47, 742, 279, 2218, 134, 567, 921, 2241, 162, 32, 183, 922, 168, 382, 174, 2242, 3323, 704, 1201, 1214, 3324, 83, 48, 443, 443, 83, 46, 3325, 2, 2243, 46, 2244, 2245, 281, 3326, 3327, 25, 71, 120, 10, 14, 14, 538, 827, 83, 3328, 71, 242, 827, 83, 1741], [1173, 15, 7, 2164, 6, 48], [61, 31, 28, 806, 28, 3, 106, 643, 118, 1171, 18, 14, 23, 3], [6, 150, 137, 34, 155, 106], [94, 247, 828, 4, 6, 353, 425, 6, 353, 1, 198, 6, 353, 1215, 6, 353, 1216, 498, 6, 353, 183, 149, 38, 6, 1, 448, 6, 353, 9, 253, 60, 38, 1036, 67, 6, 353, 31, 38, 923, 572, 6, 353, 75, 228, 257], [20, 486, 463, 999, 191, 83, 395, 14, 167, 39, 38, 1], [348, 1008, 138, 142, 1172], [1184, 330, 317, 91, 1037, 182, 96, 3329, 1438, 181, 833, 56, 323, 462, 103, 1, 64, 3330, 834, 3331, 1742, 3332, 8, 2246, 2247, 175, 194, 1157, 924, 3333, 238, 14, 71, 312, 3334, 3335, 3336, 237, 605, 3337, 3338, 16, 254, 82, 100, 655, 82, 3339, 2, 3340, 222, 3341], [1, 835, 7, 53, 173], [804, 32, 215, 215, 42, 2158, 1390, 520, 2159, 150, 593, 272, 135, 32, 151, 213, 2160, 315, 488, 2161, 168, 689], [8, 59, 131, 34, 1012, 4, 202, 808, 1399, 129, 523, 183, 109], [8, 35, 2162, 2163, 558], [836, 88, 200, 182, 539], [628, 393, 2165, 1009, 2166, 1, 1, 2167, 80], [32, 168, 72, 205, 132, 439, 440], [77, 1689, 1, 44, 367, 2149, 51, 5], [657, 49, 917, 657], [743, 97, 2248, 743, 97, 476, 538, 925, 133, 318, 2249, 18, 266, 1186, 2250, 2251, 1743, 373, 134, 63, 1217, 191, 2252, 14, 33, 2253, 3342, 7, 201, 51, 1702, 109, 306, 1038, 134, 376, 11, 3343, 705, 63, 282, 18, 18, 142, 35, 133, 1038, 3344, 46, 7, 2254, 3345, 97, 1187, 2255, 3346, 100], [112, 1176, 395, 517], [15, 3347, 3348, 477], [80, 909, 493], [177, 8, 114, 185, 8, 560, 75, 135], [278, 60, 68, 738, 259, 34], [3349, 12, 2256, 383], [92, 1039, 833, 8, 325], [28, 3, 50, 108, 112, 12, 112, 35, 23, 2, 19, 10], [69, 170, 186, 116, 59], [71, 29, 127, 92, 2180, 125], [157, 15, 10, 470, 15, 644, 902, 157, 134], [890, 791, 273, 60, 59, 152, 890, 791, 165, 926, 10, 10, 10, 136, 926, 926], [58, 1700, 58, 349, 2179, 22, 22, 57, 93], [97, 119, 2178, 97, 2, 26, 2, 729, 1395, 112, 12], [58, 837, 313, 725, 170, 695, 3, 34, 173, 78], [67, 66, 15, 904, 66, 2181, 86, 809], [15, 1439, 3350, 178, 632, 292, 136, 838, 914, 16, 1, 68], [33, 71, 52, 366, 52, 1162], [222, 744, 129, 283, 369, 416], [3351, 1218, 1440, 35], [493, 608, 104, 493, 1744, 100, 375, 741, 493, 280, 608, 1040, 702, 741, 702, 609, 447, 5, 706, 18, 32, 81, 3352, 1219, 3353, 280, 10, 608, 28, 1441, 29, 63, 10, 608, 1442, 300, 108, 1745, 1, 54, 1746, 64, 702, 407, 1182, 14, 478, 136, 282, 2257, 32, 28, 839], [92, 730, 1397, 110, 596, 4, 561, 1701, 73, 1398], [125, 399, 269, 19, 109, 14, 92, 1396, 807], [8, 54, 92, 7, 903], [1, 449, 231, 4, 96, 224, 650, 74], [257, 305, 384], [77, 12, 36, 11, 210, 44, 273, 77, 288, 320, 20, 102, 468, 2168, 594, 492, 595, 1694, 77, 2169, 2170], [1041, 71, 96, 3354, 8, 96], [1042, 65, 36, 84, 11, 2, 654], [3355, 1220, 3356, 840, 475], [13, 53, 29, 370, 13, 53, 29, 71], [49, 97, 97, 3357, 97, 3358, 816, 1747, 3359, 137, 97, 2258, 3360, 227, 236, 290, 927, 101, 22, 492, 97, 227, 33, 527], [152, 150, 113, 47, 1043, 77, 2259, 539, 246, 111, 117, 64, 385], [326, 3, 10, 96, 41, 830], [426, 1027, 61, 99, 1221, 42], [263, 745, 376, 73, 1030, 745, 100, 745, 2260, 156], [84, 384, 257, 9, 33], [25, 2261, 6, 5, 4, 70, 53, 70, 70, 19, 13, 6, 2262], [77, 658, 2263, 3361, 1443, 3362, 21, 268, 3363, 3364, 66, 241, 1444, 3365, 43, 2264, 307, 188], [111, 462, 7, 1177, 4, 9], [32, 40, 525, 32, 1204], 

In [104]:
quote.iloc[0]

'world created process thinking changed without changing thinking'

In [110]:
X = []
Y = []
for seq in sequence:
  for i in range(1, len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    Y.append(output_seq)

In [111]:
max_len = max(len(x) for x in X)
X_pad = pad_sequences(X, maxlen=max_len, padding="pre")

In [112]:
print(len(X))

38913

In [113]:
print(len(Y))

38913

In [114]:
Y = np.array(Y)

In [115]:
from tensorflow.keras.utils import to_categorical

In [116]:
Y_one_hot = to_categorical(Y, num_classes=vac_size)
print(Y_one_hot.shape)

(38913, 10000)

In [117]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout